# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 细节 · 匠心
subtitle: 小马的独立博客
description: 记录关于产品、技术以及个人的思想点滴
author: Rui Ma
author_CN: 小马
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://marui.me/
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 8
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

Plugins:
- hexo-generator-feed
- hexo-generator-sitemap

sitemap:
  path: sitemap.xml
  template:

feed:
  type: atom
  path: atom.xml
  limit: 20

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/USTCma/ustcma.github.io.git
  branch: master

#Local Search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000


algolia:
  applicationID: 'NUU03WIXJR'
  indexName: 'ruima'
  chunkSize: 5000

category_generator:
  per_page: 20

lazyload:
  enable: true

douban:
  user: i_marui
  book:
    title: '我的书单'
    quote: 记录我看过的书单。
  movie:
    title: '我的片单'
    quote: 记录我看过的电影和剧集。
  #game:
    #title: 'This is my game title'
    #quote: 'This is my game quote'
  timeout: 3000

kramed:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
